include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
  plugins: 
    - custom_lint

linter:
  rules:
    # Custom rules for better code quality
    - prefer_single_quotes
    - avoid_empty_else
    - cancel_subscriptions
    - close_sinks
    - always_declare_return_types
    - prefer_final_locals
    - prefer_final_in_for_each
    - unnecessary_const
    - unnecessary_new
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_initializing_formals